### PR TITLE
extended functionality to support nested schemas

### PR DESCRIPTION
**Pull request by AndrewGrachov**
Hey, I'm using your plugin in my work project. There are some enchancements, I added, to satisfy my needs. please, have a look

1.initialData(fields) doesnt beign passed by reference, but as entire copy.inital object stays intact
2.support for nested objects in schema any level deep
3.suport for nested schema arrays any level deep

### CODE REVIEW

**Comment by bhelx** [comment]
Thanks for sharing this! I'm gonna review as soon as I get time tonight or tomorrow.

**Comment by bhelx** [comment]
I updated the npm package to 0.4.0:

https://npmjs.org/package/mongoose-mass-assign

Thanks for the feature

**Comment by AndrewGrachov** [comment]
Thanks Benjamin! I ran some production tests and realized that some places are still require attention. Most of issues are fixed, just some UT, and expect new pull request soon :)

**Comment by bhelx** [comment]
okay thanks

**Pull request merged**
